require 'vagrant-snapshot/command/create'
require 'vagrant-snapshot/command/destroy'
require 'vagrant-snapshot/command/list'
require 'vagrant-snapshot/command/restore'
require 'vagrant-snapshot/command/root'
require 'vagrant-snapshot/command/show'
